/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.entity.Category;
import com.mycompany.entity.Product;
import com.mycompany.entity.Promotion;
import com.mycompany.service.CategoryService;
import com.mycompany.service.ProductService;
import com.mycompany.service.PromotionService;
import com.mycompany.service.impl.CategoryServiceImpl;
import com.mycompany.service.impl.ProductServiceImpl;
import com.mycompany.service.impl.PromotionServiceImpl;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ProductManagement extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiSanPhamJDialog
     */
    private Product product = null;
    private List<Object[]> list = null;
    private Object[] objPro = null;
    private List<Category> listCate = null;
    private Category category = null;
    private CategoryService categoryService = null;
//    private ColorService colorService = null;
    private Date date = new Date();
    private PromotionService promotionService = null;
    private ProductService productService = null;
    private int index = -1;
    private int rowSelected = -1;

    public ProductManagement() {
        initComponents();
        setLocationRelativeTo(null);
        fillToCategory();
        fillToProduct();
        fillToProduct2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductcatalog = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtCodeCa = new javax.swing.JTextField();
        txtNameCa = new javax.swing.JTextField();
        btnSaveCat = new javax.swing.JButton();
        btnUpdateCa = new javax.swing.JButton();
        btnDeleteCa = new javax.swing.JButton();
        btnNewCa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescription1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtProductCode1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtProductName1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnCreate1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblProduct2 = new javax.swing.JTable();
        btnRefresh1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtCreateDate1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cboColor1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cboCategory1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        rdoActive1 = new javax.swing.JRadioButton();
        rdoInactive1 = new javax.swing.JRadioButton();
        btnChoose1 = new javax.swing.JButton();
        cboSize1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        txtQuantity1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        cboPromo = new javax.swing.JComboBox<>();
        btnAd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Product Management");

        tblProductcatalog.setBackground(new java.awt.Color(204, 204, 204));
        tblProductcatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Code", "Name"
            }
        ));
        tblProductcatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductcatalogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductcatalog);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Category");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", " Product code", " Product's name", "Create Date", "Color", "Size", "Promotion Code", "Category", "Quantity", "Price", "Description", "Avaliable"
            }
        ));
        jScrollPane2.setViewportView(tblProduct);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Product");

        jLabel30.setText("Code");

        jLabel31.setText("Name");

        btnSaveCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Create.png"))); // NOI18N
        btnSaveCat.setText("Create");
        btnSaveCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCatActionPerformed(evt);
            }
        });

        btnUpdateCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnUpdateCa.setText("Update");
        btnUpdateCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCaActionPerformed(evt);
            }
        });

        btnDeleteCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnDeleteCa.setText("Delete");
        btnDeleteCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCaActionPerformed(evt);
            }
        });

        btnNewCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnNewCa.setText("New");
        btnNewCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodeCa, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameCa, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(589, 589, 589)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(602, 602, 602)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSaveCat)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateCa)
                            .addComponent(jLabel30)
                            .addComponent(txtCodeCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(txtNameCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDeleteCa))
                        .addGap(27, 27, 27)
                        .addComponent(btnNewCa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("List", jPanel2);

        txtDescription1.setColumns(20);
        txtDescription1.setRows(5);
        jScrollPane5.setViewportView(txtDescription1);

        jLabel10.setText("Product code:");

        jLabel18.setText("Product name:");

        jLabel19.setText("Size:");

        jLabel20.setText("Description:");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/627.png"))); // NOI18N

        btnCreate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Controlpanel.png"))); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Image product:");

        tblProduct2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", " Product Code", " Product Name", "Create Date", "Color", "Size", "Promotion Code", "Category", "Quantity", "Price", "Description", "Available"
            }
        ));
        tblProduct2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProduct2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblProduct2);

        btnRefresh1.setText("Refresh");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        jLabel23.setText("CreateDate:");

        txtCreateDate1.setEnabled(false);

        jLabel24.setText("Color:");

        cboColor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Violet", "Turquoise", "Light Blue", "Navy", "Limon ", "Red", "Blue", "Emerald  ", "Chlorophyll  ", "Orange", "Pink ", "Gray ", "Black", "Brown ", "Purple" }));

        jLabel25.setText("PromotionCode:");

        jLabel26.setText("Category:");

        cboCategory1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giày chạy bộ", "Giày tối giản", "Giày đi bộ", "Giày tennis", "Giày tập luyện đa năng", "Giày chạy địa hình", "Giày bóng rổ", "Giày bóng đá", "Giày da" }));

        jLabel27.setText("Avaliable:");

        buttonGroup1.add(rdoActive1);
        rdoActive1.setSelected(true);
        rdoActive1.setText("Active");

        buttonGroup1.add(rdoInactive1);
        rdoInactive1.setText("In-active");

        btnChoose1.setText("Choose File");
        btnChoose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoose1ActionPerformed(evt);
            }
        });

        cboSize1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44" }));

        jLabel28.setText("Quantity:");

        jLabel29.setText("Price:");

        cboPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM01", "KM02", "KM03", "KM04", "KM05", "KM06" }));

        btnAd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProductName1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                    .addComponent(txtProductCode1)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreateDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel29)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cboPromo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboColor1, javax.swing.GroupLayout.Alignment.LEADING, 0, 193, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCreate1)
                                    .addComponent(btnSearch1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefresh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQuantity1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboCategory1, javax.swing.GroupLayout.Alignment.LEADING, 0, 192, Short.MAX_VALUE))
                                    .addComponent(jLabel28))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(rdoActive1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(rdoInactive1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(461, 461, 461)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(btnChoose1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(210, 210, 210))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(324, 324, 324))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(btnAd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel22)
                        .addGap(83, 83, 83)
                        .addComponent(btnChoose1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboSize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoInactive1)
                                    .addComponent(rdoActive1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCreate1)
                                    .addComponent(btnUpdate1))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSearch1)
                                    .addComponent(btnRefresh1)))
                            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1367, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Product", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        if (txtProductCode1.getText().equals("") || txtProductName1.getText().equals("") || txtQuantity1.getText().equals("") || txtPrice1.getText().equals("") || txtDescription1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the information");
            return;
        }
        categoryService = new CategoryServiceImpl();
        promotionService = new PromotionServiceImpl();

        int a = JOptionPane.showConfirmDialog(this, "Do you want create ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            try {
                product = new Product();
                product.setProductCode(txtProductCode1.getText());
                product.setName(txtProductName1.getText());
                product.setSize(Integer.parseInt((String) cboSize1.getSelectedItem()));
                category = categoryService.getByCateName((String) cboCategory1.getSelectedItem());
                product.setCategory(category);
//                Color color = colorService.getByColorName((String) cboColor1.getSelectedItem());
//                Color color = new Color();
                product.setColorName((String) cboColor1.getSelectedItem());
                product.setQuantity(Integer.parseInt(txtQuantity1.getText()));
                product.setPrice(Double.parseDouble(txtPrice1.getText()));
//                colorService = new ColorServiceImpl();
//                Integer id = colorService.create(color);
//                color = colorService.getOById(id);
//                product.setColor(color);

                product.setCreateDate(date);

                Promotion pro = promotionService.getByPromoCode((String) cboPromo.getSelectedItem());
                product.setPromotion(pro);
                product.setValiable(true);
                product.setDescription(txtDescription1.getText());
//                product.setImage(lblImage.getText());

                productService = new ProductServiceImpl();
                productService.create(product);

                JOptionPane.showMessageDialog(this, "Create success");
                fillToProduct2();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Create fail");
            }
        }

    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        if (txtProductCode1.getText().equals("") || txtProductName1.getText().equals("") || txtQuantity1.getText().equals("") || txtPrice1.getText().equals("") || txtDescription1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the information");
            return;
        }
        categoryService = new CategoryServiceImpl();
        promotionService = new PromotionServiceImpl();
        productService = new ProductServiceImpl();
//        colorService = new ColorServiceImpl();
        try {
            Object[] flagObj = list.get(index);
            Integer id = Integer.parseInt(String.valueOf(flagObj[0]));
            product = productService.getProById(id);
            product.setName(txtProductName1.getText());
            product.setSize(Integer.parseInt((String) cboSize1.getSelectedItem()));
            product.setDescription(txtDescription1.getText());
            product.setValiable(rdoActive1.isSelected());

//            Color c = colorService.getColorByProduct(id);
//            System.out.println(c.toString());
            product.setColorName((String) cboColor1.getSelectedItem());
            product.setPrice(Double.parseDouble(txtPrice1.getText()));
            product.setQuantity(Integer.parseInt(txtQuantity1.getText()));

            Category cate = categoryService.getByCateName((String) cboCategory1.getSelectedItem());
            product.setCategory(cate);
            Promotion pro = promotionService.getByPromoCode((String) cboPromo.getSelectedItem());
            product.setPromotion(pro);

//            colorService.modify(c);
            productService.modify(product);

            fillToProduct2();

            JOptionPane.showMessageDialog(this, "Update success");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Update fail");
        }


    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        productService = new ProductServiceImpl();
        if (txtProductCode1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please input Product Code");
            return;
        }
        try {
            String productCode = txtProductCode1.getText();
            product = productService.getByProductCode(productCode);
            if (product != null) {
                txtProductName1.setText(product.getName());
                cboSize1.setSelectedItem(String.valueOf(product.getSize()));
                txtQuantity1.setText(String.valueOf(product.getQuantity()));
                txtPrice1.setText(String.valueOf(product.getPrice()));
                cboCategory1.setSelectedItem(product.getCategory().getName());
                txtCreateDate1.setText(datetoString(product.getCreateDate()));
                cboColor1.setSelectedItem(product.getColorName());
                cboPromo.setSelectedItem(product.getPromotion().getPromoCode());
                rdoActive1.setSelected(product.getValiable());
                txtDescription1.setText(product.getDescription());
                lblImage.setText(product.getImage());

                JOptionPane.showMessageDialog(this, "Found success");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Found fail");
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void tblProduct2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProduct2MouseClicked
        showClickProduct();
    }//GEN-LAST:event_tblProduct2MouseClicked

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        txtProductCode1.setText("");
        txtProductName1.setText("");
        cboSize1.setSelectedItem("");
        cboCategory1.setSelectedItem("");
        txtQuantity1.setText("");
        txtCreateDate1.setText("");

        cboColor1.setSelectedItem("");
        cboPromo.setSelectedItem("");
        txtPrice1.setText("");
        txtDescription1.setText("");
        lblImage.setIcon(null);
        rdoActive1.setSelected(false);
        rdoInactive1.setSelected(false);

    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void tblProductcatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductcatalogMouseClicked
        int index = tblProductcatalog.getSelectedRow();
        category = listCate.get(index);
        txtCodeCa.setText(category.getCateCode());
        txtNameCa.setText(category.getName());
    }//GEN-LAST:event_tblProductcatalogMouseClicked

    private void btnChoose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoose1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image", "jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "Select");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();

            lblImage.setIcon(new ImageIcon(f.getAbsolutePath()));
        }
    }//GEN-LAST:event_btnChoose1ActionPerformed

    private void btnSaveCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCatActionPerformed
        if (txtCodeCa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Category Code");
            return;
        } else if (txtNameCa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Category Name");
            return;
        }
        int i = JOptionPane.showConfirmDialog(this, "Do you want create ?", "Message", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            try {
                category = new Category();

                category.setCateCode(txtCodeCa.getText());
                category.setName(txtNameCa.getText());
                category.setAvailable(true);

                categoryService = new CategoryServiceImpl();
                categoryService.create(category);

                JOptionPane.showMessageDialog(this, "Save success");
                fillToCategory();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Save Fail");
            }
        }


    }//GEN-LAST:event_btnSaveCatActionPerformed

    private void btnUpdateCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCaActionPerformed
        categoryService = new CategoryServiceImpl();
        if (txtCodeCa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Category Code");
        } else if (txtNameCa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Category Name");
        }
        int i = JOptionPane.showConfirmDialog(this, "Do you want update ?", "Message", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            try {
                Integer id = category.getId();
                category = categoryService.getCateById(id);
                if (category != null) {
                    category.setCateCode(txtCodeCa.getText());
                    category.setName(txtNameCa.getText());

                    categoryService.modify(category);

                    JOptionPane.showMessageDialog(this, "Update success");
                    fillToCategory();

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Update Fail");
            }
        }
    }//GEN-LAST:event_btnUpdateCaActionPerformed

    private void btnDeleteCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCaActionPerformed
        categoryService = new CategoryServiceImpl();
        if (category == null) {
            JOptionPane.showMessageDialog(this, "Choose category pls");
        } else {
            boolean check = categoryService.remove(category.getId());
            if (check) {
                JOptionPane.showMessageDialog(this, "Remove success");
                fillToCategory();
            } else {
                JOptionPane.showMessageDialog(this, "Remove Fail");
            }
        }
    }//GEN-LAST:event_btnDeleteCaActionPerformed

    private void btnNewCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCaActionPerformed
        txtCodeCa.setText("");
        txtNameCa.setText("");
    }//GEN-LAST:event_btnNewCaActionPerformed

    private void btnAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdActionPerformed
        txtCreateDate1.setText(datetoString(date));
        txtProductCode1.setText("PRO" + getSaltString());
    }//GEN-LAST:event_btnAdActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProductManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProductManagement().setVisible(true);
//            }
//        });
//    }
    public void fillToCategory() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblProductcatalog.getModel();
        CategoryService categoryService = new CategoryServiceImpl();
        listCate = categoryService.findAll();
        defaultTableModel.setRowCount(0);
        for (Category x : listCate) {
            defaultTableModel.addRow(new Object[]{
                x.getId(), x.getCateCode(), x.getName()
            });
        }
    }

    public void fillToProduct() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblProduct.getModel();
        ProductService pro = new ProductServiceImpl();
        list = pro.findAll();
        defaultTableModel.setRowCount(0);
        for (Object[] x : list) {
            defaultTableModel.addRow(new Object[]{
                x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[10], (Boolean) x[11] ? "Active" : "Inactive"
            });
        }
    }

    public void fillToProduct2() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblProduct2.getModel();
        ProductService pro = new ProductServiceImpl();
        list = pro.findAll();
        defaultTableModel.setRowCount(0);
        for (Object[] x : list) {
            defaultTableModel.addRow(new Object[]{
                x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[10], (Boolean) x[11] ? "Active" : "Inactive"
            });
        }
    }

    public String datetoString(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }

    public void showClickProduct() {
        index = tblProduct2.getSelectedRow();
        objPro = list.get(index);
        txtProductCode1.setText((String) objPro[1]);
        txtProductName1.setText((String) objPro[2]);
        cboSize1.setSelectedItem(String.valueOf((Integer) objPro[5]));
        cboCategory1.setSelectedItem((String) objPro[7]);
        txtQuantity1.setText(String.valueOf((Integer) objPro[8]));
        txtCreateDate1.setText(((Date) objPro[3]).toString());
        cboColor1.setSelectedItem((String) objPro[4]);
        cboPromo.setSelectedItem((String) objPro[6]);
        txtPrice1.setText(String.valueOf((Double) objPro[9]));
        rdoActive1.setSelected((Boolean) objPro[11]);
        rdoInactive1.setSelected(!(Boolean) objPro[11]);
        txtDescription1.setText((String) objPro[10]);
        try {
            File file = new File("src\\main\\resources\\icon\\" + objPro[12].toString());
            Image img = ImageIO.read(file);
            lblImage.setText(null);
            int width = 312;
            int height = 242;
            lblImage.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (Exception e) {

        }
    }

    public static String getSaltString() {
        String SALTCHARS = "0123456789";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() <= 1) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAd;
    private javax.swing.JButton btnChoose1;
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnDeleteCa;
    private javax.swing.JButton btnNewCa;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSaveCat;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdateCa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCategory1;
    private javax.swing.JComboBox<String> cboColor1;
    private javax.swing.JComboBox<String> cboPromo;
    private javax.swing.JComboBox<String> cboSize1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rdoActive1;
    private javax.swing.JRadioButton rdoInactive1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblProduct2;
    private javax.swing.JTable tblProductcatalog;
    private javax.swing.JTextField txtCodeCa;
    private javax.swing.JTextField txtCreateDate1;
    private javax.swing.JTextArea txtDescription1;
    private javax.swing.JTextField txtNameCa;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtProductCode1;
    private javax.swing.JTextField txtProductName1;
    private javax.swing.JTextField txtQuantity1;
    // End of variables declaration//GEN-END:variables

    private Date dateToString(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
